# Generated by Django 6.0.5 on 2026-06-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('head0', models.CharField(default='', max_length=70)),
                ('head1', models.CharField(default='', max_length=70)),
                ('head2', models.CharField(default='', max_length=70)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('cover_photo', models.ImageField(default='', upload_to='blog/images')),
            ],
        ),
    ]
