# Generated by Django 6.0.5 on 2026-06-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_tilte_blogpost_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='about_content',
            field=models.CharField(default=' ', max_length=150),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='about_title',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
