# Generated by Django 6.0.5 on 2026-06-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_about_content_blogpost_about_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
