# Generated by Django 6.0.5 on 2026-08-02 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=150, unique=True)),
                ('parent_organization', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email_linked', models.EmailField(max_length=254)),
                ('email_vendor', models.EmailField(max_length=254)),
                ('address', models.TextField(max_length=150)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('store_banner', models.ImageField(blank=True, null=True, upload_to='store_banners/')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
