# Generated by Django 6.0.5 on 2026-07-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email_linked',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
