# Generated by Django 6.0.5 on 2026-06-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_category_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_id',
            field=models.IntegerField(default=0),
        ),
    ]
