# Generated by Django 6.0.5 on 2026-06-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_product_name_product_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_status',
            field=models.CharField(default='In Stock', max_length=20),
        ),
    ]
