# Generated by Django 6.0.5 on 2026-06-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='disc',
            new_name='desc',
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.CharField(default='', max_length=50),
        ),
    ]
