# Generated by Django 6.0.5 on 2026-06-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_status',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
