# Generated by Django 6.0.5 on 2026-06-03 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_disc_product_desc_product_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Product_id',
        ),
    ]
