# Generated by Django 6.0.5 on 2026-06-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_stock_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_now',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
