# Generated by Django 6.0.5 on 2026-07-31 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banner',
            field=models.ImageField(blank=True, help_text='User banner picture', null=True, upload_to='banners/'),
        ),
    ]
