# Generated by Django 6.0.5 on 2026-08-05 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
        ('shop', '0007_profile_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='seller.seller'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['seller', 'category'], name='shop_produc_seller__af139b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['seller', 'sub_category'], name='shop_produc_seller__7933d2_idx'),
        ),
    ]
