# Generated by Django 6.0.5 on 2026-06-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_orderupdate_alter_product_available_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_json',
            field=models.TextField(default='{}'),
        ),
    ]
