# Generated by Django 6.0.5 on 2026-06-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(default='', max_length=50)),
                ('phone_number', models.IntegerField(default='', max_length=50)),
                ('desc', models.CharField(default='', max_length=400)),
            ],
        ),
    ]
