# Generated by Django 6.0.5 on 2026-07-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order_item_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_now',
            field=models.IntegerField(),
        ),
    ]
